language: node_js

node_js:
  - "7"

script:
  - npm install -g create-elm-app@^0.6.0
  - npm test
  - npm run build

deploy:
  provider: surge
  project: ./dist/
  domain: public.apis.zone
  skip_cleanup: true
